myecho: myecho.c
	gcc -o myecho myecho.c

ex1: ex1.c iter 
	gcc -o ex1 ex1.c

ex2: ex2.c iter
	gcc -o ex2 ex2.c

ex3: ex3.c 
	gcc -o ex3 ex3.c

ex4: ex4.c 
	gcc -o ex4 ex4.c

ex5: ex5.c prime.c
	gcc -o prime prime.c
	gcc -o ex5 ex5.c

ex6: ex6.c 
	gcc -o prime prime2.c
	gcc -o ex6 ex6.c

iter: iter.c
	gcc -o iter iter.c

clean:
	rm ex1 ex2 ex3 ex4 ex5 ex6 prime iter myecho
